config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users

  authenticate :user do
    resources :timelines, only: [:index, :show], param: :username
    resources :posts, only: [:create, :show]
  end

  root to: "home#index"
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    @posts = Post.not_reply.where(user_id: [
                                    current_user.id, *current_user.followings.pluck(:id),
                                  ]).includes(postable: [:place]).order("created_at DESC")
  end

  def show
    @posts = Post.written_by(params[:username])
      .not_reply
      .order('created_at DESC')
  end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
  def on_timeline?
    controller_path == "timelines"
  end

  def on_bunch?
    on_timeline? && action_name == "index"
  end

  def on_self?
    on_timeline? && action_name == "show" &&
      params[:username] == current_user.username
  end
end

app/views/timelines/_all.html.erb
<div class="timeline">
  <% @posts.each do |post| %>
    <div class="line-group">
      <%= render 'timelines/line', post: post %>
    </div>
  <% end %>
</div>

app/views/timelines/_line.html.erb
<% user = post.user  %>
<% postable = post.postable  %>
<% show_replies = local_assigns.fetch(:show_replies, false)  %>
<%= render 'layouts/inside_modal',
title: 'Send a reply',
modal_class: "comment_modal_#{post.id}" do %>
  <%= render 'posts/form', thread: post %>
<% end %>
<div class="line flex" data-post-path="<%= post_path(post) %>" >
  <div class="profile-container">
    <%= image_tag user.profile_picture_url %>
  </div>
  <div class="content">
    <div class="identifier">
      <%= link_to timeline_path(user) do %>
        <span class="name"><%= user.name %></span>
        <span class="username">@<%= user.username %></span>
      <% end %>
    </div>
    <% if postable.is_a?(Status) %>
      <%= simple_format post.postable.text %>
    <% elsif postable.is_a?(Sight) %>
      <div class="flex items-center">
        <%= evil_icon 'ei-location' %>
        <p>
          <%= postable.humanized_activity_type %>
          <%= postable.place.name %>
        </p>
      </div>
    <% end %>
    <div class="controls">
      <%= link_to '#' do %>
        <div class="control js-modal-open"
        data-modal-class="comment_modal_<%= post.id %>"
         >
          <%= evil_icon 'ei-comment' %>
          <% if post.replies.any? %>
            <span>&nbsp;
              <%= post.replies.count %>
            </span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if post.replies.any? %>
  <div class="replies">
    <% post.replies.each do |reply| %>
      <%= render 'timelines/line', post: reply %>
    <% end %>
  </div>
<% end %>

app/views/timelines/index.html.erb
<%= render 'posts/form' %>
<%= render 'timelines/all' %>

app/views/timelines/show.html.erb
<% if on_self? %>
  <%= render 'posts/form' %>
<% end %>
<%= render 'timelines/all' %>